### ISSUE TITLE
Using this as well as Liip Functional Test Bundle?

### ISSUE THREAD

**Issue by zyphlar** [phpunit/phpunit-dom-assertions#6]
Apologies that this may not be an issue, but I'm trying to use this as well as the Liip Functional Test Bundle in my tests, which means I need to both extend their WebTestCase and your PHPUnit_Framework_DOMTestCase, but PHP doesn't do multiple inheritance. I notice you have a Trait in your code, but have been unable to use that trait in my Symfony project. Sorry if this is a newbie question, but is it possible to use both without copying/reimplementing your class?

**Comment by whatthejeff** [comment]
You should be able to extend Liip's `WebTestCase` class and use the `PHPUnit_Framework_DOMTestCase` trait in your derived class. Just make sure you include the composer autoloader and handle the namespaces appropriately.

**Comment by zyphlar** [comment]
I ended up doing MediaWiki's hack and overriding the assertTag / assertNotTag / tagMatch functions in my abstract test case to duct tape things temporarily. For those of us who really need to test XML/HTML tag structure, the lack of an upgrade path is a real deal-breaker...
