### ISSUE TITLE
PHPUnit 5.x compatibility

### ISSUE THREAD

**Issue by lstrojny** [phpunit/phpunit-dom-assertions#8]
Currently phpunit-dom-assertions blocks upgrading to PHPUnit 5.

**Comment by lstrojny** [comment]
@whatthejeff @sebastianbergmann is this project still maintained?

**Comment by photodude** [comment]
@whatthejeff what's your plan on php unit 5.x ?

**Comment by sebastianbergmann** [comment]
I have no intention on improving this or even maintaining this, sorry.

**Comment by lstrojny** [comment]
@sebastianbergmann I would take care of making sure it works with current PHPUnit versions. Wanna hand it over?

**Comment by sebastianbergmann** [comment]
Sure. Do you want to fork it or do you want to maintain it here?

**Comment by lstrojny** [comment]
@sebastianbergmann I think maintaining it here is fine.

**Comment by lstrojny** [comment]
@whatthejeff @sebastianbergmann can you set up packagist integration for this repository or hand over https://packagist.org/packages/phpunit/phpunit-dom-assertions to me and give me admin rights to this repository?

**Comment by sebastianbergmann** [comment]
I sent you a repository transfer request, @lstrojny. I cannot help you with Packagist as I do not have admin access to this package there. Only @whatthejeff can you help you with that.

**Comment by lstrojny** [comment]
@sebastianbergmann didn't receive anything from packagist yet, which email did you use?

**Comment by sebastianbergmann** [comment]
I asked GitHub to transfer this repository to you. I cannot do anything with Packagist.

**Comment by sebastianbergmann** [comment]
@lstrojny Can you please accept the project transfer? Thanks!

**Comment by lstrojny** [comment]
@sebastianbergmann I haven’t received anything unfortunately. Did you use lars@strojny.net?

**Comment by sebastianbergmann** [comment]
I did not send an email. I started a transfer of this project to your GitHub account. I would assume that GitHub sends you an email to your default email that you configured with them

**Comment by lstrojny** [comment]
@sebastianbergmann unfortunately I haven’t received anything of that kind 😢

**Comment by sebastianbergmann** [comment]
Where would I open a ticket for GitHub, then? This is getting annoying.

**Comment by photodude** [comment]
@sebastianbergmann people typically email support@github.com with issues, But I'm not sure about their response time.

**Comment by whatthejeff** [comment]
Really sorry for the delay. I've transferred the packagist project.

**Comment by lstrojny** [comment]
@whatthejeff thanks so much!
